markdown: kramdown
collections:
    pages:
        output: true
        permalink:  /:collection/:path/
buildDocs:
    deploy_remote: "origin"
    deploy_branch: "master"
    wiki_repository_url: https://github.com/Purhan/wiki-sphinx.wiki.git
    wiki_source: "_wiki"
    wiki_dest: "pages"
    commit_and_push: false
